bar:
  height: 26
  location: bottom
  font: Hack Nerd Font:pixelsize=12
  spacing: 5
  margin: 7
  layer: bottom
  background: 1d202100
  foreground: d4be98ff
  left:
    - river:
        title:
          empty: {}
        content:
          map:
            tag: occupied
            values:
              false: {empty: {}}
              true:
                - string:
                    margin: 5
                    text: "{id}"
                    foreground: 000000ff
                    deco:
                      background:
                        color: ddb071ff
                - string:
                    margin: 5
                    text: "{state}"
                    deco:
                      underline:
                        size: 2
                        color: ddb071ff

  center:
    - river:
        title:
          string:
            left-margin: 5
            right-margin: 5
            text: "{title}"
            max: 80
            deco:
              underline:
                size: 2
                color: ea6962ff
        content:
          map:
            tag: occupied
            values:
              false: {empty: {}}
              true: {empty: {}}
  right:
    - script:
        poll-interval: 1
        path: /home/uncomfy/.config/yambar/get_media.sh
        content:
          string:
            text: "{status}"
            foreground: 1DB954ff
            on-click: /home/uncomfy/.config/yambar/play_pause_media.sh
            left-margin: 5
            right-margin: 5
            deco:
              stack:
                - underline:
                   size: 2
                   color: 1DB954ff
                - background:
                   color: 191414ff

    - clock:
        time-format: "%H:%M %Z"
        content:
          - string:
              text: " {date}"
              right-margin: 5
              left-margin: 5
              foreground: 000000ff
              deco:
                  background:
                    color: d8a657ff

          - string:
              right-margin: 5
              left-margin: 5
              foreground: 000000ff
              text: " {time}"
              deco:
                  background:
                    color: d4be98ff

    - network:
        name: enp7s0
        content:
          map:
            tag: carrier
            values:
              false: {empty: {}}
              true:
                map:
                  tag: state
                  default: {string: {text: " {name}", foreground: ffffff66}}
                  values:
                    up:
                      map:
                        tag: ipv4
                        default: 
                          string:
                            foreground: 1d2021ff
                            right-margin: 5
                            left-margin: 5
                            text: " {name}"
                            deco:
                              background:
                                color: 7daea3ff
                        values:
                          "":
                            string: 
                              right-margin: 5
                              left-margin: 5
                              text: " {name}" 
                              foreground: 1d2021ff
                              deco:
                                background:
                                  color: 7daea3ff
    - battery:
        name: BAT1
        poll-interval: 30
        content:
          map:
            tag: state
            values:
              discharging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff}
                      - string: {text: , foreground: ffa600ff}
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: , foreground: 00ff00ff}
                - string: {text: " {capacity}% {estimate}"}
              charging:
                - string: {text: , foreground: 00ff00ff}
                - string: {text: " {capacity}% {estimate}"}
              full:
                - string: {text: , foreground: 00ff00ff}
                - string: {text: " {capacity}% full"}
              not charging:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: ff0000ff}
                      - string: {text:  , foreground: ffa600ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
